<a href="https://colab.research.google.com/github/Anandvardhan-25/Anand-Vardhan-Butti/blob/main/Hugging_Face_Speech_to_Text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install transformers

In [2]:
from transformers import pipeline

In [5]:
import transformers
print(transformers.__version__)

4.52.4


In [7]:
import librosa
import torch
import IPython.display as display
from transformers import Wav2Vec2ForCTC,Wav2Vec2Tokenizer
import numpy as np
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model1 = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [22]:
import librosa

audio, sampling_rate = librosa.load("/mmm.wav", sr=16000)

In [23]:
audio,sampling_rate

(array([ 1.9802092e-04, -1.7069385e-04,  7.7618824e-05, ...,
        -8.8998294e-14,  8.2389390e-14, -8.5955884e-13], dtype=float32),
 16000)

In [24]:
display.Audio('/mmm.wav',autoplay=True)

In [26]:
input_values = tokenizer(audio,return_tensors = 'pt').input_values
input_values

tensor([[0.0018, 0.0004, 0.0014,  ..., 0.0010, 0.0010, 0.0010]])

In [27]:
logits = model1(input_values).logits
logits

tensor([[[ 13.9159, -26.5882, -26.3169,  ...,  -7.5515,  -8.5245,  -8.1201],
         [ 13.8732, -26.5632, -26.2918,  ...,  -7.5623,  -8.5448,  -8.0945],
         [ 13.6505, -26.3813, -26.1312,  ...,  -7.8118,  -8.7037,  -8.3752],
         ...,
         [ 14.1130, -26.9360, -26.6202,  ...,  -6.0537,  -7.7926,  -7.5709],
         [ 14.0881, -26.9885, -26.6763,  ...,  -6.1302,  -7.8443,  -7.5416],
         [ 14.0340, -26.9564, -26.6505,  ...,  -6.3614,  -7.9499,  -7.5723]]],
       grad_fn=<ViewBackward0>)

In [28]:
predicted_ids = torch.argmax(logits,dim=-1)
predicted_ids

tensor([[ 0,  0,  0,  0,  0,  0,  0,  8, 13, 13,  0,  4, 18, 11,  0,  7,  6,  0,
          4,  4, 10, 20,  4,  4,  4,  0,  0, 12,  0,  0,  8, 17,  0,  5,  0, 24,
          0,  0,  8,  0, 14,  0, 22, 22,  4,  4,  4,  0,  5,  0, 15,  0,  0, 12,
          5,  0,  4,  0, 19,  0,  8, 16, 15,  0, 14,  4, 14,  0,  8,  0,  4,  4,
          6, 11,  5,  4,  4,  4, 17, 10, 12, 12,  0, 12, 12, 10,  0,  8,  9,  0,
          0,  0,  4,  4, 24,  0,  0,  5,  6,  0,  0,  0,  6,  5, 13, 13,  4,  4,
          6, 11,  0,  7,  9,  4,  4,  4, 22,  0,  0,  0,  8, 16,  0,  0,  0,  4,
          4,  4,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 18, 11,  0,  7,  6,  0,  4, 10, 20,  4,  4, 22,  0,
          8, 16,  0,  4,  4,

In [30]:
transcriptions = tokenizer.decode(predicted_ids[0])
transcriptions

"OR WHAT IF SOMEBODY ELSE COULD DO THE MISSION BETTER THAN YOU WHAT IF YOU THOUGHT YOU COULDN'T DO IT IT WOULD YOUR DUTY BE THEN"